apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
	
	
	path('registro/', views.RegistroUsuario.as_view(), name='registro'),
	path('editar/', views.ModificarUsuario.as_view(), name='editar'),
	
	]

pruebaUsuario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index, name='index'),
    path('Login' , auth.LoginView.as_view(template_name="usuarios/login.html") , name='login'),
    path('Logout' , auth.LogoutView.as_view() , name='logout'),

    path('usuarios/', include('apps.usuarios.urls')),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
    provincia = models.CharField(max_length=30, null=True)
    ciudad = models.CharField(max_length=30, null=True)
    universidad = models.CharField(max_length=50, null=True)
    carrera = models.CharField(max_length=50, null=True)
    pass

apps/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Usuario

class RegistroUsuarioForm(UserCreationForm):
	class Meta:
		model = Usuario
		fields = ['username',
				'first_name',
				'last_name',				
				'password1',
				'password2',]
		exclude = ['email',
				'provincia',
				'ciudad',
				'universidad',
				'carrera']
		help_texts = {
				'username': None,
				'password1': None,
				'password2': None,
			}

class EditarUsuarioForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = ['email',
				'provincia',
				'ciudad',
				'universidad',
				'carrera']

apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import RegistroUsuarioForm, EditarUsuarioForm
from .models import Usuario
from django.contrib.auth import login, authenticate



class RegistroUsuario(CreateView):
    model = Usuario
    form_class = RegistroUsuarioForm
    template_name = 'usuarios/registro.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        '''
        En este parte, si el formulario es valido guardamos lo que se obtiene de él y 
        usamos authenticate para que el usuario incie sesión luego de haberse registrado 
        y lo redirigimos al index
        '''

        form.save()
        usuario = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        usuario = authenticate(username=usuario, password=password)
        login(self.request, usuario)
        return redirect('/')

class ModificarUsuario(UpdateView):
    model = Usuario
    form_class = EditarUsuarioForm
    template_name = 'usuarios/editar.html'
    success_url = reverse_lazy('index')

    def get_object(self):
        return self.request.user

pruebaUsuario/views.py
from django.shortcuts import render, redirect

def Index(request):
	return render(request, 'index.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
		<!--CREO UN BLOQUE CSS DONDE SOLO DEBEN ESTAR LOS CSS DE LA BASE, EL RESTO SE AGREGA EN CADA TEMPLATE -->
		{% block css %}
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	
			<link rel="stylesheet" type="text/css" href="{% static 'portada/css/base.css' %}">
		{% endblock %}
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	
		<!-- CREO UN BLOQUE TITULO, PARA AGREGAR EL TITULO EN CADA TEMPLATE-->
		<title>{% block titulo %}{% endblock %}</title>
		
	</head>
<body>
	<header>
	<!--IMAGEN PRINCIPAL-->
		<div class="container-fuild d-flex justify-content-center imagenlogo">			
			<img src="{% static 'portada/image/LogoINFORINGA-01.png' %}" width="150" height="auto" class="img-responsive align-center d-md-none d-lg-block d-sm-none d-md-block d-none d-sm-block" alt="Responsive image">
		</div>		
	<!--FIN DE IMAGEN PRINCIPAL-->
	</header>
	<!--NAVBAR-->
	<nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #007F5F;">
		<a class="navbar-brand text-white" href="{% url 'index' %}">
			<img src="{% static 'portada/image/INFORINGAlogochiquito.png' %}" width="40" height="40" class="d-inline-block align-top" alt="" loading="logo">				
		</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>		  
		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<div class="text-center mr-auto">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a href="#" class="btn btn-success">Crear Post</a>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link text-white" href="#">Ultimos Posteos</a>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link text-white">Ultimos Comentarios</a>
					</li>					
				</ul>				
			</div>
			<div class="d-flex justify-content-center">				
				{% if user.is_authenticated %}
				<div>
					<a href="{% url 'usuarios:editar' %}" class="btn btn-danger mr-2 text-uppercase" style="background-color: #BF6300;">BIENVENIDO {{user.username}}</a>
				</div>
				<div>
					<a href="{% url 'logout' %}" class="btn btn-danger mr-2" style="background-color: #BF6300;">SALIR</a>
				</div>
				{% else %}	
				<div>
					<div>
						<a href="{% url 'usuarios:registro' %}" class="btn btn-danger mr-2" style="background-color: #BF6300;">REGISTRARSE</a>
						<a href="{% url 'login' %}" class="btn btn-danger mr-2" style="background-color: #BF6300;">ACCEDER</a>
					</div>
				</div>
				{% endif %}
			</div>				
		</div>						
	</nav>
	<!--FIN NAVBAR-->		
    <div class="container mt-4 mb-4">        
        {% block contenido %}
    
        {% endblock %}        
    </div>	
	<!--FOOTER-->
	<footer id="sticky-footer" class="py-4 text-white" style="background-color: #007F5F;">
		<div class="container text-center" >
		  <small>Copyright &copy; Your Website</small>
		</div>
	</footer>
	<!--FIN DEL FOOTER-->
	
	<!--CAMBIO EL BLOCK DE CONTENIDOS DE JS AL FINAL, PORQUE ASI EVITA UNA CARGA INNECESARIA AL PRINCIPIO DE LA WEB(YA QUE SON PESADOS) Y NO AFECTA AL FUNCIONAMIENTO DE LA MISMA-->
<!-- 	{% block js %} -->

	<!-- {% endblock %} -->
</body>
</html>

<!-- {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
CSS only href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

JS, Popper.js, and jQuery -3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
	{% if user.is_authenticated %}
		<p>Bienvenido {{user.username}} {{user.first_name}} {{user.last_name}} {{user.provincia}} {{user.universidad}} {{user.carrera}} </p>
		<a href="{% url 'logout' %}">logout</a>
		<a href="{% url 'usuarios:editar' %}">editar</a>
	{% else %}
		<a href="{% url 'usuarios:registro' %}">registro</a>
		<a href="{% url 'login' %}">login</a>
	{% endif %}
	
   </body>
   </html> -->

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}  
	<p ><h1 style="color:white;">index</h1></p>

	{% if user.is_authenticated %}
	
		<p style="color:white;">Bienvenido {{user.username}} {{user.first_name}} {{user.last_name}} {{user.provincia}} {{user.universidad}} {{user.carrera}} </p>
		
	{% endif %}

	
	{% endblock contenido %}

templates/usuarios/editar.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}  

<!-- Modal -->
<form method="POST"> {% csrf_token %}
<div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ingreso de Usuarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <table border="1">
          {{form.errors}}
          {{ form | crispy }}
         </table>
      </div>
      <div class="modal-footer">
        <button type="button" onclick="history.back()" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Ingresar</button>
      </div>
    </div>
  </div>
</div>
	        
        
    </form>


    <script>
      $(document).ready(function()
      {
         $("#basicExampleModal").modal("show");
      });
</script>
{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}  

<!-- Modal -->
<form method="POST"> {% csrf_token %}
<div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ingreso de Usuarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <table border="1">
          {{form.errors}}
          {{ form | crispy }}
         </table>
      </div>
      <div class="modal-footer">
        
        <button type="button" onclick="history.back()" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Ingresar</button>
      </div>
    </div>
  </div>
</div>
	        
        
    </form>


    <script>
      $(document).ready(function()
      {
         $("#basicExampleModal").modal("show");
      });
</script>
{% endblock contenido %}

templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}  

<!-- Modal -->
<form method="POST"> {% csrf_token %}
<div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Registro de Usuarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <table border="1">
          {{form.errors}}
          {{ form | crispy }}
         </table>
      </div>
      <div class="modal-footer">
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <button type="button" onclick="history.back()"class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Registrarse</button>
      </div>
    </div>
  </div>
</div>
          
        
    </form>


    <script>
      $(document).ready(function()
      {
         $("#basicExampleModal").modal("show");
      });
</script>
{% endblock contenido %}